<a href="https://colab.research.google.com/github/tanisaur/ML_zoomcamp/blob/main/ML_Homework_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Set up the environment
You need to install Python, NumPy, Pandas, Matplotlib and Seaborn.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


Q1. Pandas version

What's the version of Pandas that you installed?

You can get the version information using the __version__ field:
`pd.__version__`

In [4]:
pd.__version__

'2.2.2'

Get the data

In [6]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

--2024-10-02 01:29:06--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: ‘laptops.csv’

laptops.csv         100%[===================>] 291.58K  --.-KB/s    in 0.04s   

2024-10-02 01:29:06 (6.74 MB/s) - ‘laptops.csv’ saved [298573/298573]



In [7]:
data = pd.read_csv('laptops.csv')

Q2. Records count

How many records are in the dataset?

    12
    1000
    2160
    12160


In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


Q3. Laptop brands

How many laptop brands are presented in the dataset?

    12
    27
    28
    2160


In [10]:
brands = data['Brand'].unique()
print(len(brands))


27


Q4. Missing values

How many columns in the dataset have missing values?

    0
    1
    2
    3


In [11]:
columns_with_missing_values = data.columns[data.isnull().any()].tolist()
print(len(columns_with_missing_values))


3


Q5. Maximum final price

What's the maximum final price of Dell notebooks in the dataset?

    869
    3691
    3849
    3936


In [21]:
dell_laptops = data[data['Brand'] == 'Dell']
max_dell_price = dell_laptops['Final Price'].max()
print(max_dell_price)


3936.0


Q6. Median value of Screen

In [22]:
# 1. Find the median value of Screen column in the dataset.
median_screen = data['Screen'].median()
print(median_screen)

15.6


In [24]:
# 2. Next, calculate the most frequent value of the same Screen column.
most_frequent_screen = data['Screen'].mode()[0]
print(most_frequent_screen)


15.6


In [25]:
# 3. Use fillna method to fill the missing values in Screen column with
#    the most frequent value from the previous step.
data['Screen'].fillna(most_frequent_screen, inplace=True)

<ipython-input-25-d81e0d18ae88>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Screen'].fillna(most_frequent_screen, inplace=True)


In [26]:
# 4. Now, calculate the median value of Screen once again.
median_screen_after_fillna = data['Screen'].median()
print(median_screen_after_fillna)

15.6


Has it changed? No.

Q7. Sum of weights

In [27]:
# 1. Select all the "Innjoo" laptops from the dataset.
innjoo_laptops = data[data['Brand'] == 'Innjoo']

In [29]:
# 2. Select only columns RAM, Storage, Screen.
selected_columns = innjoo_laptops[['RAM', 'Storage', 'Screen']]

In [33]:
# 3. Get the underlying NumPy array. Let's call it X.
X = selected_columns.values

In [34]:
# 4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = np.dot(X.T, X)
print(XTX)

[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


In [35]:
# 5. Compute the inverse of XTX.
XTX_inverse = np.linalg.inv(XTX)
print(XTX_inverse)

[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


In [37]:
# 6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [38]:
# 7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = np.dot(np.dot(XTX_inverse, X.T), y)

In [39]:
# 8. What's the sum of all the elements of the result?
sum_w = np.sum(w)
print(sum_w)

91.2998806299555
